[project]
name = "polycalendar"
dynamic = ["version"]
description = "calendar synthesis software"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.9",
    "cuddly-dicts>=3.0.2",
    "hypercorn>=0.17.3",
    "ics>=0.7.2",
    "pydantic>=2.11.5",
    "starlette>=0.47.0",
    "typer>=0.16.0",
]

[project.scripts]
polycalendar = "polycalendar.__main__:app"

[project.entry-points."polycalendar.transformations"]
null = "polycalendar.transformations.null:null_transformer"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "./polycalendar/__about__.py"
